# Generated by Django 5.1.7 on 2025-03-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(max_length=15, unique=True)),
                ("education", models.CharField(max_length=255)),
                ("specialization", models.CharField(max_length=100)),
                (
                    "training_status",
                    models.CharField(
                        choices=[("Ongoing", "Ongoing"), ("Completed", "Completed")],
                        default="Ongoing",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interns",
                        to="hospital.hospital",
                    ),
                ),
                (
                    "supervising_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interns",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.customuser",
                    ),
                ),
            ],
        ),
    ]
