# Generated by Django 5.1.7 on 2025-03-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_remove_customuser_groups_and_more"),
        ("interns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "intern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_patients",
                        to="hospital.intern",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_interns",
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Intern",
        ),
    ]
