# Generated by Django 5.1.7 on 2025-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupervisedIntern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
    ]
