# Generated by Django 5.1.7 on 2025-03-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_assignedpatient_supervisedintern_and_more"),
        ("hospital", "0002_remove_customuser_groups_and_more"),
        ("interns", "0002_assignedpatient_delete_intern"),
        ("patients", "0002_appointment_medicalrecord_delete_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedpatient",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_patients",
                to="hospital.doctor",
            ),
        ),
        migrations.AddField(
            model_name="assignedpatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_doctors",
                to="hospital.patient",
            ),
        ),
        migrations.AddField(
            model_name="supervisedintern",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervised_interns",
                to="hospital.doctor",
            ),
        ),
        migrations.AddField(
            model_name="supervisedintern",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervising_doctor",
                to="hospital.intern",
            ),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
