# Generated by Django 5.1.7 on 2025-03-24 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_assignedpatient_doctor_assignedpatient_patient_and_more"),
        ("hospital", "0002_remove_customuser_groups_and_more"),
        ("interns", "0002_assignedpatient_delete_intern"),
        ("patients", "0002_appointment_medicalrecord_delete_patient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
    ]
